"""[ Made token type as 'Bearer' instead of 'bearer'. ]

Revision ID: 231baea5963e
Revises: bb97a7ad9d2d
Create Date: 2026-08-12 05:30:43.635372

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '231baea5963e'
down_revision: str | None = 'bb97a7ad9d2d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###